"""Tests for _sfv_verified_complete — cross-checks a release's .sfv manifest
against what's actually on disk. Regression test for a real incident:
Underworld: Evolution had only 2 of 87 expected RAR volumes on disk, but one
of the two present was the LAST volume, so the older last-file-only check
(_release_complete) was fooled into treating it as done.
"""
from pathlib import Path

from dcbridge.util import _sfv_verified_complete


def _write_sfv(d: Path, filenames: list[str]) -> None:
    sfv = d / "release.sfv"
    lines = ["; Generated by test\n"]
    lines += [f"{name} DEADBEEF\n" for name in filenames]
    sfv.write_text("".join(lines), encoding="utf-8")


def test_all_expected_files_present_verifies_complete(tmp_path):
    names = [f"release.r{i:02d}" for i in range(3)] + ["release.rar"]
    _write_sfv(tmp_path, names)
    for name in names:
        (tmp_path / name).write_bytes(b"x")
    assert _sfv_verified_complete(tmp_path) is True


def test_underworld_evolution_incident_only_first_and_last_volume_present(tmp_path):
    # Real case: SFV expects r00..r86 + .rar (88 files), only r00 and .rar
    # actually landed on disk. The last-file-only heuristic would call this
    # "complete" (the .rar exists); the manifest cross-check must not.
    names = [f"release.r{i:02d}" for i in range(87)] + ["release.rar"]
    _write_sfv(tmp_path, names)
    (tmp_path / "release.r00").write_bytes(b"x")
    (tmp_path / "release.rar").write_bytes(b"x")
    assert _sfv_verified_complete(tmp_path) is False


def test_missing_a_single_middle_volume_is_not_complete(tmp_path):
    names = [f"release.r{i:02d}" for i in range(5)] + ["release.rar"]
    _write_sfv(tmp_path, names)
    for name in names:
        if name == "release.r02":
            continue  # one volume silently missing
        (tmp_path / name).write_bytes(b"x")
    assert _sfv_verified_complete(tmp_path) is False


def test_no_sfv_file_returns_none_not_false(tmp_path):
    (tmp_path / "release.rar").write_bytes(b"x")
    assert _sfv_verified_complete(tmp_path) is None


def test_missing_directory_returns_none(tmp_path):
    assert _sfv_verified_complete(tmp_path / "does-not-exist") is None


def test_filename_matching_is_case_insensitive(tmp_path):
    _write_sfv(tmp_path, ["Release.R00", "Release.RAR"])
    (tmp_path / "release.r00").write_bytes(b"x")
    (tmp_path / "release.rar").write_bytes(b"x")
    assert _sfv_verified_complete(tmp_path) is True


def test_sfv_comment_lines_are_ignored(tmp_path):
    sfv = tmp_path / "release.sfv"
    sfv.write_text("; a comment\n; another\nrelease.rar DEADBEEF\n", encoding="utf-8")
    (tmp_path / "release.rar").write_bytes(b"x")
    assert _sfv_verified_complete(tmp_path) is True


def test_extra_files_beyond_the_manifest_dont_matter(tmp_path):
    _write_sfv(tmp_path, ["release.rar"])
    (tmp_path / "release.rar").write_bytes(b"x")
    (tmp_path / "release.nfo").write_bytes(b"x")  # not in the manifest, irrelevant
    assert _sfv_verified_complete(tmp_path) is True
