"""Tests for _sfv_verified_complete — cross-checks a release's .sfv manifest
against what's actually on disk. Regression test for a real incident:
Underworld: Evolution had only 2 of 87 expected RAR volumes on disk, but one
of the two present was the LAST volume, so the older last-file-only check
(_release_complete) was fooled into treating it as done.
"""
from pathlib import Path

from dcbridge.util import _sfv_verified_complete


def _write_sfv(d: Path, filenames: list[str]) -> None:
    sfv = d / "release.sfv"
    lines = ["; Generated by test\n"]
    lines += [f"{name} DEADBEEF\n" for name in filenames]
    sfv.write_text("".join(lines), encoding="utf-8")


def test_all_expected_files_present_verifies_complete(tmp_path):
    names = [f"release.r{i:02d}" for i in range(3)] + ["release.rar"]
    _write_sfv(tmp_path, names)
    for name in names:
        (tmp_path / name).write_bytes(b"x")
    assert _sfv_verified_complete(tmp_path) is True


def test_underworld_evolution_incident_only_first_and_last_volume_present(tmp_path):
    # Real case: SFV expects r00..r86 + .rar (88 files), only r00 and .rar
    # actually landed on disk. The last-file-only heuristic would call this
    # "complete" (the .rar exists); the manifest cross-check must not.
    names = [f"release.r{i:02d}" for i in range(87)] + ["release.rar"]
    _write_sfv(tmp_path, names)
    (tmp_path / "release.r00").write_bytes(b"x")
    (tmp_path / "release.rar").write_bytes(b"x")
    assert _sfv_verified_complete(tmp_path) is False


def test_missing_a_single_middle_volume_is_not_complete(tmp_path):
    names = [f"release.r{i:02d}" for i in range(5)] + ["release.rar"]
    _write_sfv(tmp_path, names)
    for name in names:
        if name == "release.r02":
            continue  # one volume silently missing
        (tmp_path / name).write_bytes(b"x")
    assert _sfv_verified_complete(tmp_path) is False


def test_no_sfv_file_returns_none_not_false(tmp_path):
    (tmp_path / "release.rar").write_bytes(b"x")
    assert _sfv_verified_complete(tmp_path) is None


def test_missing_directory_returns_none(tmp_path):
    assert _sfv_verified_complete(tmp_path / "does-not-exist") is None


def test_filename_matching_is_case_insensitive(tmp_path):
    _write_sfv(tmp_path, ["Release.R00", "Release.RAR"])
    (tmp_path / "release.r00").write_bytes(b"x")
    (tmp_path / "release.rar").write_bytes(b"x")
    assert _sfv_verified_complete(tmp_path) is True


def test_sfv_comment_lines_are_ignored(tmp_path):
    sfv = tmp_path / "release.sfv"
    sfv.write_text("; a comment\n; another\nrelease.rar DEADBEEF\n", encoding="utf-8")
    (tmp_path / "release.rar").write_bytes(b"x")
    assert _sfv_verified_complete(tmp_path) is True


def test_extra_files_beyond_the_manifest_dont_matter(tmp_path):
    _write_sfv(tmp_path, ["release.rar"])
    (tmp_path / "release.rar").write_bytes(b"x")
    (tmp_path / "release.nfo").write_bytes(b"x")  # not in the manifest, irrelevant
    assert _sfv_verified_complete(tmp_path) is True


# ── _release_complete_on_disk (combines the .sfv check with a fallback) ─────
from dcbridge.util import _release_complete_on_disk


def test_on_disk_missing_folder_is_incomplete(tmp_path):
    # parent (season dir) exists, the release folder does not
    assert _release_complete_on_disk(tmp_path / "Release.S01E01-GRP") is False


def test_on_disk_unreadable_parent_is_none(tmp_path):
    assert _release_complete_on_disk(tmp_path / "no" / "such" / "Release-GRP") is None


def test_on_disk_no_sfv_but_has_rar_first_volume_is_complete(tmp_path):
    d = tmp_path / "Release-GRP"; d.mkdir()
    (d / "x.r00").write_bytes(b"x")
    (d / "x.rar").write_bytes(b"x")
    assert _release_complete_on_disk(d) is True


def test_on_disk_no_sfv_no_rar_first_volume_is_incomplete(tmp_path):
    # the Reacher S04E02 shape: .rNN volumes but no .rar and no .sfv
    d = tmp_path / "Release-GRP"; d.mkdir()
    for i in range(11):
        (d / f"x.r{i:02d}").write_bytes(b"x")
    (d / "x.nfo").write_bytes(b"x")
    assert _release_complete_on_disk(d) is False


def test_on_disk_no_sfv_but_has_video_is_complete(tmp_path):
    d = tmp_path / "Release-GRP"; d.mkdir()
    (d / "x.mkv").write_bytes(b"x")
    assert _release_complete_on_disk(d) is True


def test_on_disk_failing_sfv_beats_a_present_rar(tmp_path):
    d = tmp_path / "Release-GRP"; d.mkdir()
    names = [f"x.r{i:02d}" for i in range(5)] + ["x.rar"]
    (d / "x.sfv").write_text("".join(f"{n} DEADBEEF\n" for n in names), encoding="utf-8")
    (d / "x.rar").write_bytes(b"x")   # only the last volume landed
    assert _release_complete_on_disk(d) is False
